(()=>{
const BANK=(window.QUESTION_BANK||[]), AVAILABLE=BANK.filter(q=>q.available!==false&&q.answer);const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LS_W='guqin_wrong_v4',LS_S='guqin_session_v4';let installPrompt=null;const st={view:'home',cat:null,quiz:[],answers:{},idx:0,result:null};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>[...new Set(String(x||'').toUpperCase().split('').filter(c=>'ABCD'.includes(c)))].sort().join('');
const catName=c=>c==='中级/高级'?'中高级':c;const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1800)}
function save(){if(!st.quiz.length)return;localStorage.setItem(LS_S,JSON.stringify({cat:st.cat,ids:st.quiz.map(q=>q.id),answers:st.answers,idx:st.idx}))}
function restore(){try{let s=JSON.parse(localStorage.getItem(LS_S)||'null');if(!s)return false;let m=new Map(AVAILABLE.map(q=>[q.id,q])),q=s.ids.map(id=>m.get(id)).filter(Boolean);if(!q.length)return false;Object.assign(st,{view:'quiz',cat:s.cat,quiz:q,answers:s.answers||{},idx:Math.min(s.idx||0,q.length-1)});return true}catch{return false}}
function wrongs(){try{return JSON.parse(localStorage.getItem(LS_W)||'[]')}catch{return []}}
function addWrong(arr){let m=new Map(wrongs().map(x=>[x.id,x]));arr.forEach(q=>{let x=m.get(q.id)||{id:q.id,count:0};x.count++;x.mine=norm(st.answers[q.id])||'未作答';m.set(q.id,x)});localStorage.setItem(LS_W,JSON.stringify([...m.values()]))}
function explain(q,open=false){return `<details class="result-item" ${open?'open':''}><summary style="padding:14px;font-weight:800;cursor:pointer">查看详细解析</summary><div class="explain"><b>为什么选：</b>${esc(q.why||q.explanation||'暂无')}<br><br><b>背景补充：</b>${esc(q.background||'暂无补充')}${q.anomaly&&q.anomaly!=='正常'?`<br><br><b>题库提示：</b>${esc(q.anomaly)}`:''}</div></details>`}
function home(){let a=AVAILABLE.filter(q=>q.category==='初级').length,b=AVAILABLE.filter(q=>q.category==='中级/高级').length;return `<section class="hero"><span class="eyebrow">题库已内置 · 无需登录</span><h2>古琴考级题库<br>边练 · 边懂 · 边记</h2><p>每次随机抽取20题，以“网络核验答案”判分。每题解析增加“为什么选”和“背景补充”，帮助你理解人物、琴曲、琴谱与历史典故。</p></section>
<section class="install-card"><b>📱 可以安装到手机桌面</b><p>iPhone 用 Safari 打开本网站 → 分享 → 添加到主屏幕；Android 用 Chrome 打开 → 菜单 → 安装应用/添加到主屏幕。</p><div class="install-row"><button id="installBtn" class="btn primary hidden">安装应用</button></div></section>
<div class="section-title"><h3>开始练习</h3><span>每次随机20题</span></div><div class="grid"><div class="level-card"><strong>初级题库</strong><small>古琴基础、形制、指法、传统文化</small><div class="count">${a}</div><button class="btn primary" data-start="初级">随机20题</button></div><div class="level-card"><strong>中高级题库</strong><small>琴史、琴派、曲目、琴学与进阶知识</small><div class="count">${b}</div><button class="btn primary" data-start="中级/高级">随机20题</button></div></div>
<div class="feature-list"><div class="feature"><div class="ico">✓</div><div><b>自动评分</b><p>单选、多选均按网络核验答案判分，交卷后显示答案和详细解析。</p></div></div><div class="feature"><div class="ico">▤</div><div><b>错题本</b><p>错题保存在当前手机浏览器，记录错误次数，可随时随机重练。</p></div></div><div class="feature"><div class="ico">⌕</div><div><b>拍照识题</b><p>上传或拍摄题目截图，OCR后在本题库中匹配题号、答案和解析。</p></div></div></div>`}
function start(cat,ids){let pool=AVAILABLE.filter(q=>q.category===cat);if(ids){let s=new Set(ids);pool=pool.filter(q=>s.has(q.id))}st.cat=cat;st.quiz=shuffle(pool).slice(0,Math.min(20,pool.length));st.answers={};st.idx=0;st.result=null;st.view='quiz';save();render()}
function quiz(){let q=st.quiz[st.idx];if(!q)return home();let sel=new Set(String(st.answers[q.id]||'').split(''));let done=Object.values(st.answers).filter(Boolean).length;return `<div class="page-head"><div><h2>${catName(st.cat)}练习</h2><p>第 ${st.idx+1} / ${st.quiz.length} 题 · 已作答 ${done} 题</p></div><button class="btn ghost" data-home>退出</button></div><div class="quiz-meta"><div class="progress-track"><div class="progress-fill" style="width:${(st.idx+1)/st.quiz.length*100}%"></div></div><span class="progress-text">${st.idx+1}/${st.quiz.length}</span></div><article class="question-card"><div class="q-tags"><span class="tag">${catName(q.category)} 第${q.number}题</span>${q.isMulti?'<span class="tag multi">多选题</span>':''}</div><h3 class="q-title">${esc(q.question)}</h3><div class="options">${Object.entries(q.options||{}).map(([k,v])=>`<button class="option ${sel.has(k)?'selected':''}" data-opt="${k}"><span class="letter">${k}</span><span class="option-text">${esc(v)}</span></button>`).join('')}</div></article><div class="quiz-actions"><button class="btn ghost" data-prev ${st.idx===0?'disabled':''}>上一题</button>${st.idx<st.quiz.length-1?'<button class="btn primary" data-next>下一题</button>':'<button class="btn primary" data-submit>交卷评分</button>'}</div>`}
function submit(){let missing=st.quiz.filter(q=>!norm(st.answers[q.id])).length;if(missing&&!confirm(`还有 ${missing} 题未作答，仍然交卷吗？`))return;let good=st.quiz.filter(q=>norm(st.answers[q.id])===norm(q.answer)),bad=st.quiz.filter(q=>norm(st.answers[q.id])!==norm(q.answer));st.result={good:good.length,bad:bad.length,score:Math.round(good.length/st.quiz.length*100)};addWrong(bad);localStorage.removeItem(LS_S);st.view='result';render()}
function result(){let r=st.result||{good:0,bad:0,score:0};return `<section class="score-card"><div class="big">${r.score}</div><h2>${r.score>=90?'掌握得很好':r.score>=75?'不错，继续巩固':r.score>=60?'再复习一轮':'重点看看错题解析'}</h2><p>${catName(st.cat)} · 本次 ${st.quiz.length} 题</p><div class="score-stats"><div class="stat"><b>${r.good}</b><span>答对</span></div><div class="stat"><b>${r.bad}</b><span>答错</span></div><div class="stat"><b>${st.quiz.length}</b><span>总题数</span></div></div></section><div class="quiz-actions"><button class="btn ghost" data-view="wrong">看错题本</button><button class="btn primary" data-again>再练20题</button></div><div class="section-title"><h3>逐题答案与解析</h3><span>错题自动展开</span></div><div class="result-list">${st.quiz.map((q,i)=>{let ok=norm(st.answers[q.id])===norm(q.answer);return `<article class="result-item ${ok?'correct':'wrong'}"><div class="result-head"><div class="${ok?'ok-badge':'wrong-badge'}">${ok?'✓ 回答正确':'✕ 回答错误'}</div><b>${i+1}. ${esc(q.question)}</b><div class="answer-line">你的答案：<strong>${esc(norm(st.answers[q.id])||'未作答')}</strong><br>正确答案：<strong>${esc(q.answerContent||q.answer)}</strong></div></div>${explain(q,!ok)}</article>`}).join('')}</div>`}
function wrongPage(){let map=new Map(AVAILABLE.map(q=>[q.id,q])),items=wrongs().map(x=>({x,q:map.get(x.id)})).filter(z=>z.q).sort((a,b)=>b.x.count-a.x.count);return `<div class="page-head"><div><h2>错题本</h2><p>${items.length} 道错题 · 保存在当前设备</p></div></div>${items.length?`<div class="wrong-actions"><button class="btn primary" data-retry>随机重练错题</button><button class="btn danger" data-clear>清空错题</button></div><div class="wrong-list">${items.map(({x,q})=>`<article class="wrong-card"><div class="meta"><span>${catName(q.category)} 第${q.number}题</span><span>累计错 ${x.count} 次</span></div><h4>${esc(q.question)}</h4><div class="ans">正确答案：<strong>${esc(q.answerContent||q.answer)}</strong></div>${explain(q)}</article>`).join('')}</div>`:'<div class="empty"><div class="big-ico">✓</div>还没有错题。去做一组随机练习吧。</div>'}`}
function ocrPage(){return `<div class="page-head"><div><h2>拍照识题</h2><p>拍照 / 上传截图 → OCR → 匹配题库答案</p></div></div><section class="ocr-card"><div class="upload-box"><input id="ocrFile" type="file" accept="image/*" capture="environment"><label for="ocrFile"><div class="camera">⌕</div><h3>拍照或上传题目截图</h3><p>尽量让题干清楚、完整，减少无关画面。</p></label><img id="preview" class="preview hidden"></div><div id="ocrStatus" class="privacy-note">也可以直接把题目文字粘贴到下方搜索。</div><textarea id="ocrText" class="textarea" placeholder="OCR文字会出现在这里；也可手动粘贴题干……"></textarea><button class="btn primary full" data-search>搜索题库答案</button></section><div id="matches"></div>`}
function sim(a,b){let clean=s=>String(s||'').replace(/[\s\p{P}\p{S}]/gu,'').toLowerCase();a=clean(a);b=clean(b);if(!a||!b)return 0;if(b.includes(a)||a.includes(b))return .98;let A=new Set([...a].map((_,i)=>a.slice(i,i+2)).filter(x=>x.length===2)),B=new Set([...b].map((_,i)=>b.slice(i,i+2)).filter(x=>x.length===2)),n=0;A.forEach(x=>B.has(x)&&n++);return 2*n/(A.size+B.size||1)}
function searchText(t){let ms=AVAILABLE.map(q=>({q,s:sim(q.question,t)})).sort((a,b)=>b.s-a.s).slice(0,5).filter(x=>x.s>.12),box=$('#matches');box.innerHTML=`<div class="section-title"><h3>匹配结果</h3><span>按相似度排序</span></div>${ms.length?ms.map(({q,s})=>`<article class="wrong-card"><div class="meta"><span>${catName(q.category)} 第${q.number}题</span><span>匹配 ${Math.round(s*100)}%</span></div><h4>${esc(q.question)}</h4><div class="ans">答案：<strong>${esc(q.answerContent||q.answer)}</strong></div>${explain(q,s>.5)}</article>`).join(''):'<div class="empty">没有找到足够相似的题目，请让照片更清晰或复制完整题干。</div>'}`;box.scrollIntoView({behavior:'smooth'})}
async function ocr(file){let status=$('#ocrStatus'),txt=$('#ocrText');try{status.textContent='正在加载中文识别组件并识别题目…';if(!window.Tesseract){await new Promise((ok,no)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}let w=await Tesseract.createWorker('chi_sim+eng');let r=await w.recognize(file);await w.terminate();txt.value=r.data.text||'';status.textContent='识别完成，已自动搜索题库';searchText(txt.value)}catch(e){console.error(e);status.textContent='OCR识别失败，请直接粘贴题目文字搜索。'}}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>{st.view=b.dataset.view;render()});$$('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start));let h=$('[data-home]');if(h)h.onclick=()=>{save();st.view='home';render()};let q=st.quiz[st.idx];$$('[data-opt]').forEach(b=>b.onclick=()=>{let k=b.dataset.opt;if(q.isMulti){let s=new Set(String(st.answers[q.id]||'').split('').filter(Boolean));s.has(k)?s.delete(k):s.add(k);st.answers[q.id]=[...s].sort().join('')}else st.answers[q.id]=k;save();render()});let p=$('[data-prev]');if(p)p.onclick=()=>{st.idx=Math.max(0,st.idx-1);save();render()};let n=$('[data-next]');if(n)n.onclick=()=>{st.idx=Math.min(st.quiz.length-1,st.idx+1);save();render()};let sub=$('[data-submit]');if(sub)sub.onclick=submit;let again=$('[data-again]');if(again)again.onclick=()=>start(st.cat);let retry=$('[data-retry]');if(retry)retry.onclick=()=>{let ids=wrongs().map(x=>x.id),pool=AVAILABLE.filter(q=>ids.includes(q.id));if(!pool.length)return;st.cat='错题重练';st.quiz=shuffle(pool).slice(0,20);st.answers={};st.idx=0;st.view='quiz';save();render()};let clear=$('[data-clear]');if(clear)clear.onclick=()=>{if(confirm('确定清空全部错题记录吗？')){localStorage.removeItem(LS_W);render()}};let f=$('#ocrFile');if(f)f.onchange=e=>{let x=e.target.files[0];if(!x)return;let im=$('#preview');im.src=URL.createObjectURL(x);im.classList.remove('hidden');ocr(x)};let se=$('[data-search]');if(se)se.onclick=()=>{let t=$('#ocrText').value.trim();t?searchText(t):toast('请先拍照或输入题目文字')};let ib=$('#installBtn');if(ib){if(installPrompt)ib.classList.remove('hidden');ib.onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast('iPhone 请用 Safari 的“分享 → 添加到主屏幕”')}}}
function render(){let v=$('#view');v.innerHTML=st.view==='quiz'?quiz():st.view==='result'?result():st.view==='wrong'?wrongPage():st.view==='ocr'?ocrPage():home();$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===(['quiz','result'].includes(st.view)?'home':st.view)));bind()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;let b=$('#installBtn');if(b)b.classList.remove('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});restore();render();
})();
