(()=>{
const BANK = window.QUESTION_BANK || [];
const AVAILABLE = BANK.filter(q=>q.available && q.answer);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const LS_WRONG='guqin_wrong_v4', LS_SESSION='guqin_session_v4';
const state={view:'home',category:null,quiz:[],answers:{},index:0,submitted:false,result:null,bankCategory:'全部',bankQuery:''};
const UA=navigator.userAgent||'';
const IS_WECHAT=/MicroMessenger/i.test(UA);
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function catLabel(c){return c==='中级/高级'?'中高级':c==='错题重练'?'错题重练':'初级'}
function countCat(c){return AVAILABLE.filter(q=>q.category===c).length}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function ansNorm(v){return [...new Set(String(v||'').toUpperCase().split('').filter(c=>'ABCD'.includes(c)))].sort().join('')}
function selected(id){return ansNorm(state.answers[id])}
function isCorrect(q){return selected(q.id)===ansNorm(q.answer)}
function saveSession(){if(!state.quiz.length||state.submitted){localStorage.removeItem(LS_SESSION);return}localStorage.setItem(LS_SESSION,JSON.stringify({category:state.category,quizIds:state.quiz.map(q=>q.id),answers:state.answers,index:state.index}))}
function restoreSession(){try{const s=JSON.parse(localStorage.getItem(LS_SESSION)||'null');if(!s||!Array.isArray(s.quizIds))return false;const map=new Map(AVAILABLE.map(q=>[q.id,q]));const quiz=s.quizIds.map(id=>map.get(id)).filter(Boolean);if(!quiz.length)return false;Object.assign(state,{view:'quiz',category:s.category,quiz,answers:s.answers||{},index:Math.min(s.index||0,quiz.length-1),submitted:false,result:null});return true}catch{return false}}
function setView(v){state.view=v;render()}
function homeHTML(){const has=!!localStorage.getItem(LS_SESSION);return `<div class="home-grid"><button class="category-card" data-start="初级"><div class="big">初级练习</div><p>古琴基础、形制、指法、传统文化</p><div class="count-num">${countCat('初级')}</div><div class="card-btn">开始练习</div></button><button class="category-card" data-start="中级/高级"><div class="big">中高级练习</div><p>琴史、琴派、曲目、琴学与进阶知识</p><div class="count-num">${countCat('中级/高级')}</div><div class="card-btn">开始练习</div></button></div>${has?`<div style="margin-top:12px"><button class="btn secondary full" data-action="resume">继续上次练习</button></div>`:''}`}
function startQuiz(cat,ids=null){state.category=cat;let pool=AVAILABLE.filter(q=>q.category===cat);if(ids){const set=new Set(ids);pool=pool.filter(q=>set.has(q.id))}state.quiz=shuffle(pool).slice(0,Math.min(20,pool.length));state.answers={};state.index=0;state.submitted=false;state.result=null;state.view='quiz';saveSession();render()}
function quizHTML(){const q=state.quiz[state.index];if(!q)return homeHTML();const pct=Math.round(((state.index+1)/state.quiz.length)*100);const vals=new Set((state.answers[q.id]||'').split(''));return `<div class="page-head"><div><h2>${catLabel(state.category)}练习</h2><p>第 ${state.index+1} / ${state.quiz.length} 题 · 已答 ${Object.keys(state.answers).filter(k=>state.answers[k]).length} 题</p></div><button class="btn ghost" data-action="quit">退出</button></div><div class="progress-wrap"><div class="progress" style="width:${pct}%"></div></div><article class="question-card"><div class="q-meta"><span class="tag">${catLabel(q.category)} 第${q.number}题</span><span class="q-num">${q.isMulti?'多选题':'单选题'}</span></div><h3>${esc(q.question)}</h3>${q.isMulti?'<div class="multi-tip">可选择多个选项</div>':''}<div class="option-list">${Object.entries(q.options).map(([k,v])=>`<div class="option ${vals.has(k)?'selected':''}" data-opt="${k}"><span class="opt-letter">${k}</span><span class="opt-text">${esc(v)}</span></div>`).join('')}</div></article><div class="quiz-actions"><button class="btn ghost" data-action="prev" ${state.index===0?'disabled':''}>上一题</button>${state.index<state.quiz.length-1?'<button class="btn primary" data-action="next">下一题</button>':'<button class="btn primary" data-action="submit">交卷评分</button>'}</div><div class="answer-count">答案会自动保存，返回后可继续</div>`}
function toggleOption(q,k){if(q.isMulti){const s=new Set((state.answers[q.id]||'').split('').filter(Boolean));s.has(k)?s.delete(k):s.add(k);state.answers[q.id]=[...s].sort().join('')}else state.answers[q.id]=k;saveSession();render()}
function submitQuiz(){const unanswered=state.quiz.filter(q=>!selected(q.id)).length;if(unanswered && !confirm(`还有 ${unanswered} 题未作答，确定现在交卷吗？`))return;const correct=state.quiz.filter(isCorrect),wrong=state.quiz.filter(q=>!isCorrect(q));state.result={correct:correct.length,wrong:wrong.length,score:Math.round(correct.length/state.quiz.length*100)};state.submitted=true;updateWrongBook(wrong);localStorage.removeItem(LS_SESSION);state.view='result';render()}
function updateWrongBook(wrong){const by=new Map(getWrongBook().map(x=>[x.id,x]));wrong.forEach(q=>{const x=by.get(q.id)||{id:q.id,count:0,lastSelected:'',updatedAt:''};x.count++;x.lastSelected=selected(q.id)||'未作答';x.updatedAt=new Date().toISOString();by.set(q.id,x)});localStorage.setItem(LS_WRONG,JSON.stringify([...by.values()]))}
function getWrongBook(){try{return JSON.parse(localStorage.getItem(LS_WRONG)||'[]')}catch{return []}}
function explainHTML(q,open=false){return `<details class="explain-details" ${open?'open':''}><summary>查看详细解析 ▾</summary><div class="explain-box"><div class="explain-part"><b>为什么选</b>${esc(q.why||'暂无')}</div><div class="explain-part bg"><b>背景补充</b>${esc(q.background||'暂无')}</div>${q.anomaly&&q.anomaly!=='正常'?`<div class="anomaly"><b>题库提示：</b>${esc(q.anomaly)}${q.pdfAnswer&&ansNorm(q.pdfAnswer)!==ansNorm(q.answer)?`；PDF原答案：${esc(q.pdfAnswer)}，本程序判分答案：${esc(q.answer)}`:''}</div>`:''}</div></details>`}
function resultHTML(){const r=state.result||{score:0,correct:0,wrong:0};return `<section class="score-card"><div class="score-num">${r.score}</div><h2>${r.score>=90?'很稳':r.score>=75?'不错，继续巩固':r.score>=60?'再复盘一轮':'重点看错题解析'}</h2><p>${catLabel(state.category)} · 本次 ${state.quiz.length} 题</p><div class="score-grid"><div class="score-kpi"><b>${r.correct}</b><span>答对</span></div><div class="score-kpi"><b>${r.wrong}</b><span>答错</span></div><div class="score-kpi"><b>${state.quiz.length}</b><span>总题数</span></div></div></section><div class="quiz-actions" style="margin:14px 0"><button class="btn ghost" data-action="wrong">查看错题本</button><button class="btn primary" data-action="again">再练20题</button></div><div class="section-title"><h3>逐题答案与解析</h3><span>点击展开查看</span></div><div class="result-list">${state.quiz.map((q,i)=>{const ok=isCorrect(q),mine=selected(q.id)||'未作答';return `<article class="result-item ${ok?'':'wrong'}"><div class="result-head"><span class="status ${ok?'ok':'bad'}">${ok?'✓ 回答正确':'✕ 回答错误'}</span><h4>${i+1}. ${esc(q.question)}</h4><div class="answer-line">你的答案：<strong>${esc(mine)}</strong><br>正确答案：<strong>${esc(q.answerContent||q.answer)}</strong></div></div>${explainHTML(q,false)}</article>`}).join('')}</div>`}
function wrongHTML(){const map=new Map(AVAILABLE.map(q=>[q.id,q]));const items=getWrongBook().map(m=>({m,q:map.get(m.id)})).filter(x=>x.q).sort((a,b)=>b.m.count-a.m.count);return `<div class="page-head"><div><h2>错题本</h2><p>保存在本机浏览器 · 不需要登录</p></div></div>${items.length?`<div class="wrong-tools"><button class="btn primary" data-action="retry-wrong">随机重练错题</button><button class="btn danger" data-action="clear-wrong">清空错题</button></div><div class="wrong-list">${items.map(({m,q})=>`<article class="wrong-item"><div class="wrong-top"><span class="tag">${catLabel(q.category)} 第${q.number}题</span><span class="count-pill">错 ${m.count} 次</span></div><h4>${esc(q.question)}</h4><div class="answer-line">正确答案：<strong>${esc(q.answerContent||q.answer)}</strong><br>上次选择：${esc(m.lastSelected||'未记录')}</div>${explainHTML(q,false)}</article>`).join('')}</div>`:`<div class="empty">还没有错题。去首页做题后，错题会自动出现在这里。</div>`}`}
function retryWrong(){const ids=getWrongBook().map(x=>x.id);const map=new Map(AVAILABLE.map(q=>[q.id,q]));const valid=ids.map(id=>map.get(id)).filter(Boolean);if(!valid.length)return toast('暂无错题');state.category='错题重练';state.quiz=shuffle(valid).slice(0,Math.min(20,valid.length));state.answers={};state.index=0;state.submitted=false;state.result=null;state.view='quiz';saveSession();render()}
function bankItems(){let items=AVAILABLE;if(state.bankCategory!=='全部')items=items.filter(q=>q.category===state.bankCategory);const kw=normalizeText(state.bankQuery);if(kw){items=items.filter(q=>normalizeText(q.question+Object.values(q.options).join('')+(q.why||'')+(q.background||'')).includes(kw))}return items}
function bankHTML(){const items=bankItems();return `<div class="page-head"><div><h2>题库</h2><p>按分类查看题目、答案和解析</p></div></div><div class="bank-toolbar"><div class="seg">${['全部','初级','中级/高级'].map(c=>`<button class="${state.bankCategory===c?'active':''}" data-bank-cat="${c}">${c==='中级/高级'?'中高级':c}</button>`).join('')}</div><input id="bankSearch" class="search-input" placeholder="搜索题目关键词" value="${esc(state.bankQuery)}"></div><div class="section-title"><h3>${state.bankCategory==='全部'?'全部题目':catLabel(state.bankCategory)+'题库'}</h3><span>${items.length} 题</span></div>${items.length?`<div class="bank-list">${items.map(q=>`<article class="bank-item"><div class="bank-top"><span class="tag">${catLabel(q.category)} 第${q.number}题</span><span class="q-num">${q.isMulti?'多选题':'单选题'}</span></div><h4>${esc(q.question)}</h4><div class="bank-options">${Object.entries(q.options).map(([k,v])=>`<div class="bank-opt">${k}. ${esc(v)}</div>`).join('')}</div><div class="bank-answer">答案：${esc(q.answerContent||q.answer)}</div>${explainHTML(q,false)}</article>`).join('')}</div>`:`<div class="empty">没有匹配到题目，请换个关键词试试。</div>`}`}
function ocrHTML(){return `<div class="page-head"><div><h2>拍照识题</h2><p>拍照 / 相册 → OCR → 匹配题库</p></div></div>${IS_WECHAT?'<div class="wechat-tip">微信内置浏览器也可上传图片；如果相机调用或OCR加载受限，请点右上角“…”改用 Safari / Chrome 打开。</div>':''}<section class="ocr-card card"><div class="upload-zone"><input id="ocrFile" type="file" accept="image/*" capture="environment"><label for="ocrFile"><div class="camera">▣</div><h3>拍照或上传题目截图</h3><p>建议只保留一道题，题干和选项尽量完整清晰。</p></label><img id="ocrPreview" class="preview hidden" alt="题目图片"></div><div id="ocrStatus" class="ocr-status">未选择图片</div><div class="ocr-progress"><span id="ocrBar"></span></div><div class="section-title"><h3>识别文字</h3><span>也可以直接粘贴题目</span></div><textarea id="ocrText" placeholder="OCR结果会出现在这里；也可以手动粘贴或输入题干……"></textarea><div style="margin-top:9px"><button class="btn primary full" data-action="match-text">搜索题库答案</button></div></section><div id="matchWrap" class="hidden"><div class="section-title"><h3>匹配结果</h3><span>按相似度排序</span></div><div id="matchResults" class="match-list"></div></div>`}
function normalizeText(s){return String(s||'').toLowerCase().replace(/[\s\p{P}\p{S}]/gu,'').replace(/[—_－-]+/g,'').replace(/[0-9０-９]+/g,m=>m)}
function ngrams(s,n=2){const set=new Set();if(s.length<n){if(s)set.add(s);return set}for(let i=0;i<=s.length-n;i++)set.add(s.slice(i,i+n));return set}
function sim(a,b){a=normalizeText(a);b=normalizeText(b);if(!a||!b)return 0;if(a.includes(b)||b.includes(a))return .995;const A=ngrams(a),B=ngrams(b);let inter=0;A.forEach(x=>{if(B.has(x))inter++});const dice=(2*inter)/(A.size+B.size||1);let chars=0;for(const ch of new Set(a)){if(b.includes(ch))chars++}const cr=chars/(new Set(a).size||1);return Math.min(.99,dice*.72+cr*.28)}
function scoreOCRText(s){const t=String(s||'');const zh=(t.match(/[\u4e00-\u9fff]/g)||[]).length;const ascii=(t.match(/[A-Za-z]/g)||[]).length;const digits=(t.match(/[0-9]/g)||[]).length;return zh*3 + digits + ascii*.2}
function extractQueries(text){const raw=String(text||'').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/[—_－]/g,'一');const lines=raw.split(/\n+/).map(s=>s.trim()).filter(Boolean);const good=lines.filter(s=>s.replace(/[^\u4e00-\u9fffA-Da-d0-9]/g,'').length>=6);const qline=good.filter(s=>/[？?]/.test(s) || /[琴古曲谱徽弦指法]/.test(s));const merged=(qline.slice(0,2).join(' ')) || good.slice(0,3).join(' ') || raw;const out=[raw, merged, ...good.slice(0,5)];return [...new Set(out.map(s=>s.trim()).filter(Boolean))]}
function parseNumber(text){const m=String(text||'').match(/(?:^|\D)(\d{1,3})[、.．]/);return m?Number(m[1]):null}
function parseCat(text){text=String(text||'');if(/中高级|中级|高级/.test(text))return '中级/高级'; if(/初级/.test(text))return '初级'; return null}
function findMatches(text){const queries=extractQueries(text);const num=parseNumber(text);const cat=parseCat(text);return AVAILABLE.map(q=>{const base=q.question+' '+Object.entries(q.options).map(([k,v])=>`${k}${v}`).join(' ');let score=0;queries.forEach(s=>{score=Math.max(score,sim(base,s),sim(q.question,s)*1.02)});if(num&&q.number===num)score=Math.min(.995,score+0.08);if(cat&&q.category===cat)score=Math.min(.995,score+0.04);return {q,score}}).sort((a,b)=>b.score-a.score).slice(0,5).filter(x=>x.score>.11)}
function confidence(s){if(s>.72)return ['高匹配',''];if(s>.46)return ['较匹配',''];return ['可能匹配','low']}
function renderMatches(text){const wrap=$('#matchWrap'),box=$('#matchResults');if(!wrap||!box)return;const ms=findMatches(text);wrap.classList.remove('hidden');if(!ms.length){box.innerHTML='<div class="empty">没有找到足够相似的题目。建议裁剪图片，只保留一道题，或手动修正OCR文字后再搜索。</div>';return}box.innerHTML=ms.map(({q,score})=>{const [lab,cls]=confidence(score);return `<article class="match-card"><div class="match-top"><span class="tag">${catLabel(q.category)} 第${q.number}题</span><span class="confidence ${cls}">${lab} ${Math.round(score*100)}%</span></div><h4>${esc(q.question)}</h4><div class="match-answer">答案：${esc(q.answerContent||q.answer)}</div>${explainHTML(q,false)}</article>`}).join('');wrap.scrollIntoView({behavior:'smooth',block:'start'})}
async function loadTesseract(){if(window.Tesseract)return;if(window.__tessP)return window.__tessP;window.__tessP=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return window.__tessP}
async function preprocessForOCR(file){const url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();const maxW=1600;const scale=Math.min(1,maxW/img.width);const w=Math.max(1,Math.round(img.width*scale)), h=Math.max(1,Math.round(img.height*scale));const cvs=document.createElement('canvas');cvs.width=w;cvs.height=h;const ctx=cvs.getContext('2d');ctx.drawImage(img,0,0,w,h);const data=ctx.getImageData(0,0,w,h);let minX=w,minY=h,maxX=0,maxY=0,found=false;for(let y=0;y<h;y++){for(let x=0;x<w;x++){const i=(y*w+x)*4;const gray=(data.data[i]+data.data[i+1]+data.data[i+2])/3;if(gray<238){found=true;if(x<minX)minX=x;if(y<minY)minY=y;if(x>maxX)maxX=x;if(y>maxY)maxY=y}}}if(!found){URL.revokeObjectURL(url);return file}const pad=18;minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX=Math.min(w-1,maxX+pad);maxY=Math.min(h-1,maxY+pad);const cw=maxX-minX+1,ch=maxY-minY+1;const out=document.createElement('canvas');out.width=Math.min(2200, Math.round(cw*2));out.height=Math.min(2200, Math.round(ch*2));const octx=out.getContext('2d');octx.fillStyle='#fff';octx.fillRect(0,0,out.width,out.height);octx.drawImage(cvs,minX,minY,cw,ch,0,0,out.width,out.height);const id=octx.getImageData(0,0,out.width,out.height);for(let i=0;i<id.data.length;i+=4){let g=(id.data[i]*0.299+id.data[i+1]*0.587+id.data[i+2]*0.114);g=(g-128)*1.5+128;g=Math.max(0,Math.min(255,g));if(g>210)g=255;id.data[i]=id.data[i+1]=id.data[i+2]=g}octx.putImageData(id,0,0);URL.revokeObjectURL(url);const blob=await new Promise(r=>out.toBlob(r,'image/png'));return blob||file}
async function recognizeWith(worker,input){const ret=await worker.recognize(input,{rotateAuto:true},{tessedit_pageseg_mode:Tesseract.PSM.SINGLE_BLOCK});return ret.data.text||''}
async function doOCR(file){const status=$('#ocrStatus'),bar=$('#ocrBar'),text=$('#ocrText');try{status.textContent='正在加载中文识别组件…';bar.style.width='5%';await loadTesseract();const worker=await Tesseract.createWorker(['chi_sim','eng'],1,{logger:m=>{if(m.progress!=null)bar.style.width=`${Math.max(6,Math.round(m.progress*100))}%`;if(m.status)status.textContent=({'loading tesseract core':'加载识别核心','initializing tesseract':'初始化识别器','loading language traineddata':'加载中文模型','initializing api':'初始化中文模型','recognizing text':'正在识别题目'}[m.status]||m.status)}});const prep=await preprocessForOCR(file);let best=await recognizeWith(worker,prep);if(scoreOCRText(best)<24){status.textContent='正在进行二次识别…';const text2=await recognizeWith(worker,file);if(scoreOCRText(text2)>scoreOCRText(best))best=text2}await worker.terminate();text.value=best||'';bar.style.width='100%';status.textContent='识别完成，已自动匹配题库';renderMatches(text.value)}catch(e){console.error(e);status.textContent='OCR加载失败。请确认网络正常，或直接把题目文字粘贴到下方搜索。';toast('OCR失败，可改用文字搜索')}}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-start]').forEach(b=>b.onclick=()=>startQuiz(b.dataset.start));const resume=$('[data-action="resume"]');if(resume)resume.onclick=()=>{if(!restoreSession())toast('没有可恢复的练习');render()};const q=state.quiz[state.index];$$('[data-opt]').forEach(o=>o.onclick=()=>toggleOption(q,o.dataset.opt));const prev=$('[data-action="prev"]');if(prev)prev.onclick=()=>{state.index=Math.max(0,state.index-1);saveSession();render()};const next=$('[data-action="next"]');if(next)next.onclick=()=>{state.index=Math.min(state.quiz.length-1,state.index+1);saveSession();render()};const sub=$('[data-action="submit"]');if(sub)sub.onclick=submitQuiz;const quit=$('[data-action="quit"]');if(quit)quit.onclick=()=>{if(confirm('退出后会保留当前答题进度。')){saveSession();setView('home')}};const wrong=$('[data-action="wrong"]');if(wrong)wrong.onclick=()=>setView('wrong');const again=$('[data-action="again"]');if(again)again.onclick=()=>startQuiz(state.category);const clear=$('[data-action="clear-wrong"]');if(clear)clear.onclick=()=>{if(confirm('确定清空全部错题记录吗？')){localStorage.removeItem(LS_WRONG);render()}};const retry=$('[data-action="retry-wrong"]');if(retry)retry.onclick=retryWrong;const file=$('#ocrFile');if(file)file.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const p=$('#ocrPreview');p.src=URL.createObjectURL(f);p.classList.remove('hidden');doOCR(f)};const match=$('[data-action="match-text"]');if(match)match.onclick=()=>{const t=$('#ocrText').value.trim();if(!t)return toast('请先上传图片或输入题目文字');renderMatches(t)};$$('[data-bank-cat]').forEach(b=>b.onclick=()=>{state.bankCategory=b.dataset.bankCat;render()});const bankSearch=$('#bankSearch');if(bankSearch)bankSearch.onchange=e=>{state.bankQuery=e.target.value;render()}}
function render(){const v=$('#view');if(state.view==='quiz')v.innerHTML=quizHTML();else if(state.view==='result')v.innerHTML=resultHTML();else if(state.view==='wrong')v.innerHTML=wrongHTML();else if(state.view==='ocr')v.innerHTML=ocrHTML();else if(state.view==='bank')v.innerHTML=bankHTML();else v.innerHTML=homeHTML();$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===(['quiz','result'].includes(state.view)?'home':state.view)));bind();$$('.wrong-item .explain-details,.bank-item .explain-details,.match-card .explain-details,.result-item .explain-details').forEach(d=>d.removeAttribute('open'))}
if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(!restoreSession())state.view='home';render();
})();